- name: install samba package (Redhat)
  tags: samba
  yum:
          name: samba
          state: latest
- name: start samba
  systemd:
          name: smb
          state: started
          enabled: yes

