---

- hosts: all
  become: true
  tasks:
          - name: install httpd and php for CentOS
            dnf:
                    name:
                        - httpd
                        - php
                    update_cache: yes
                    state: latest
            
