---

- hosts: all
  become: true
  tasks:
          - name: install httpd, php, and update_cache for CentOS
            dnf:
                    name: 
                        - httpd
                        - php,php-mysqlnd
                        - update_cache
                    name: '*'
                    state: latest
                   
          - name: run httpd
            systemd:
                    name: httpd
                    state: started
                    enabled: yes

          - name: Allow HTTP traffic
            firewalld:

                    service: http
                    permanent: yes
                    state: enabled
                    immediate: yes

          - name: Reload firewalld
            command: firewall-cmd --reload

