---

- hosts: all
  become: true
  tasks:
          - name: update repository index
            dnf:
                    state:latest

          - name: install httpd
            dnf:
                    name: httpd
                    state: absent

          - name: run httpd
            systemd:
                    name: httpd
                    state: started
                    enabled: yes
  tasks:

          - name: Allow HTTP traffic
            firewalld:

                    service: http
                    permanent: yes
                    state: enabled
                    immediate: yes

          - name: Reload firewalld
            command: firewall-cmd --reload

  tasks:
          - name: Install PHP packages
            dnf:
                    name: php,php-mysqlnd
                    state: absent

          - name: Configure Apache to use PHP
            lineinfile:
                    path: /etc/httpd/conf/httpd.conf
                    regexp: '^#AddHandler php'
                    line: 'AddHandler php-script .php'
                    state: absent
                    backup: yes

          - name: Restart Apache
            systemd:
                    name: httpd
                    state: restarted
                    enabled: yes
