---

- hosts: all
  become: true
  pre_tasks:

          - name: install updates (Redhat)
            dnf:
                    update_only: yes
                    
- hosts: web_server
  become: true
  tasks: 
        
          - name: install httpd and php for Redhat server
            yum:
                    name:
                            - httpd
                            - php
                    state: latest

- hosts: db_server
  become: true
  tasks:
          - name: install mariadb package (Redhat)
            yum:
                    name: mariadb
                    state: latest
- hosts: file_server
  become: true
  tasks:
          - name: install samba package (Redhat)
            yum:
                    name: samba
                    state: latest
          - name: start samba
            systemd:
                    name: smb
                    state: started
                    enabled: yes


- name: Install Nagios on RHEL
  hosts: nagios_server
  become: yes

  tasks:
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - php
        - gcc
        - glibc
        - glibc-common
        - gd
        - gd-devel
        - make
        - net-snmp
        - openssl-devel
        - xinetd
        - unzip

    - name: Download Nagios Core
      get_url:
        url: "https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz"
        dest: "/tmp/nagioscore.tar.gz"

    - name: Extract Nagios Core
      ansible.builtin.unarchive:
        src: "/tmp/nagioscore.tar.gz"
        dest: "/tmp/nagioscore"
        remote_src: yes

    - name: Compile and install Nagios Core
      command: chdir=/tmp/nagioscore/nagioscore-nagios-4.4.6 ./configure --with-httpd-conf=/etc/httpd/conf.d
    - command: chdir=/tmp/nagioscore/nagioscore-nagios-4.4.6 make all
    - command: chdir=/tmp/nagioscore/nagioscore-nagios-4.4.6 make install

    - name: Install Nagios Plugins
      command: chdir=/tmp/nagioscore/nagioscore-nagios-4.4.6/plugins make
    - command: chdir=/tmp/nagioscore/nagioscore-nagios-4.4.6/plugins make install

    - name: Create Nagios User and Group
      user:
        name: nagios
        groups: http

    - name: Enable and start httpd service
      service:
        name: httpd
        enabled: yes
        state: started
