---

- hosts: all
  become: true
  pre_tasks:

          - name: install updates (Redhat)
            tags: always
            dnf:
                    update_only: yes
                    
- hosts: web_server
  become: true
  tasks: 
        
          - name: install httpd and php for Redhat server
            tags: apache,centos,httpd
            yum:
                    name:
                            - httpd
                            - php
                    state: latest

- hosts: db_server
  become: true
  tasks:
          - name: install mariadb package (Redhat)
            tags: centos,bd,mariadb
            yum:
                    name: mariadb
                    state: latest
- hosts: file_server
  become: true
  tasks:
          - name: install samba package (Redhat)
            tags: samba
            yum:
                    name: samba
                    state: latest
          - name: start samba
            systemd:
                    name: smb
                    state: started
                    enabled: yes
