---
- hosts: all
  become: true
  pre_tasks:
    - name: update repository index (CentOS)
      tags: always
      dnf:
        update_only: yes

- hosts: all
  become: true
  roles:
          - base

- hosts: db_servers
  become: true
  roles:
          - db_servers

- hosts: file_servers
  become: true
  roles:
          - file_servers

- hosts: web_servers
  become: true
  roles:
          - web_servers

