---

- hosts: all
  become: true
  pre_tasks:

          - name: install updates (Redhat)
            tags: always
            dnf:
                    update_only: yes

          - name: add ssh key for simone
            tags: always
            authorized_key:
                    user: simone
                    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINt1VjXhGXwwuMMNXsv8dKvKbiTKHazsjlO/FahGIo/f ansible"
                    state: present         
                    
