- name: install httpd and php for Redhat server
  tags: apache,centos,httpd,php
  package:
          name:
                  - "{{ apache_package_name }}"
                  - "{{ php_package_name }}"
          state: latest
         
- name: start and enable httpd (Rhel)
  tags: apache,httpd
  service:
          name: "{{ apache_service }}"
          state: started
          enabled: yes
